AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Guardfile
    - Rakefile
    - Thorfile

# This must be disabled for compatibility with knife-cookbook-doc.
Style/LeadingCommentSpace:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - Guardfile

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - metadata.rb
