AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Guardfile
    - Rakefile
    - Thorfile

Style/RegexpLiteral:
  Exclude:
    - Guardfile

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - metadata.rb
