language: ruby
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2

before_install: 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
install: bundle install --without=integration
script: bundle exec rake travis
