language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.1
  - 2.1.2

before_install: 'echo ''gem: --no-document'' > ~/.gemrc'
install:
  - bundle install --without=integration
  - bundle update
script: bundle exec rake travis
