language: ruby
rvm: [ 2.2.2 ]
cache: bundler
sudo: false

before_install: 'echo ''gem: --no-document'' > ~/.gemrc'

install:
  - bundle install --without=integration
  - bundle update

script: bundle exec rake travis
