name             'replace_cookbook'
maintainer       'replace_your_name'
maintainer_email 'replace_email@example.com'
license          'Apache 2.0'
description      'replace_description.'
source_url       'https://github.com/replace_username/replace_repo'
issues_url       'https://github.com/replace_username/replace_repo/issues'
version          '0.0.0'

recipe 'replace_cookbook::default', 'replace_description.'
