name             'replace_cookbook_name'
maintainer       'replace_your_name'
maintainer_email 'replace_email@example.com'
license          'Apache 2.0'
description      'replace_description'
version          '0.0.0'
